{"name": "test_right_way", "status": "skipped", "statusDetails": {"message": "XFAIL Wait for fix bug\n\nselenium.common.exceptions.TimeoutException: Message:", "trace": "tests\\test_shop.py:80: in test_right_way\n    WebDriverWait(browser, timeout=10, poll_frequency=2).until(\n        browser    = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"99bdab286359ab6465b0c078ecf41677\")>\n        product    = <selenium.webdriver.remote.webelement.WebElement (session=\"99bdab286359ab6465b0c078ecf41677\", element=\"1d045a24-1557-484d-b6b7-f38ee8ed518a\")>\nenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: in until\n    raise TimeoutException(message, screen, stacktrace)\nE   selenium.common.exceptions.TimeoutException: Message:\n        end_time   = 623350.593\n        message    = ''\n        method     = <function visibility_of_element_located.<locals>._predicate at 0x000001D7B96CB740>\n        screen     = None\n        self       = <selenium.webdriver.support.wait.WebDriverWait (session=\"99bdab286359ab6465b0c078ecf41677\")>\n        stacktrace = None\n        value      = False"}, "description": "\n    Test case TC-4\n    ", "start": 1678717031976, "stop": 1678717045049, "uuid": "bfee29c5-8602-437d-8bc8-355de4abbfb9", "historyId": "832350b147fac251f172289a626c5cba", "testCaseId": "7b8323124234f69a8fde1e3de50f452e", "fullName": "tests.test_shop#test_right_way", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Wait for fix bug')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_shop"}, {"name": "host", "value": "DESKTOP-Q8DJUUR"}, {"name": "thread", "value": "980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_shop"}]}